### ISSUE TITLE
[BUG] Sessions are never validated by default

### ISSUE THREAD

**Issue by beckler** [riverrun/phauxth#109]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```[bash]
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```
* Operating system: 
`macOS 10.13.6`

### Current behavior

After adding the phauxth lib to my project (via the generator), once a user is logged in, their session is never validated. Removing the value from the sessions table does not prevent a user that is already logged in from accessing resources.

### Expected behavior

When the session is deleted from the table, the targeted user should no longer be able to bypass the newly required authorization.

### Additional information

This may be a known issue, but I assumed based on #41 and the [Sessions Wiki page](https://github.com/riverrun/phauxth/wiki/Sessions), that this behavior already existed.

**Comment by riverrun** [comment]
Could you check to see if the `current_user` is being set for the protected resource? You can do this by running `IO.inspect conn.assigns` in the controller function of the protected resource.

**Comment by riverrun** [comment]
First of all, sorry for the delay in getting back to you - I haven't felt too good the last few days.

I think the issue is that the `Phauxth.Remember` plug is creating a new session because there is still a `remember_me` cookie present. Could you check if that is the case by adding `IO.inspect conn.req_cookies` in the controller function? If a `remember_me` cookie is there, then it is working as expected, and if not, there is a problem.

**Comment by beckler** [comment]
Ah okay, the `remember_me` cookie is probably present then, as I'm fairly certain I have it hard coded it in the default session path.

Thank you for responding! And thank you for this awesome library!
