### ISSUE TITLE
Multiple user models, authorization and other questions

### ISSUE THREAD

**Issue by dsignr** [riverrun/phauxth#12]
I guess my issue could be split into multiple parts:
1. How can I setup authentication for a model other than user?
2. How can I setup multiple user models (eg. buyer, seller, etc.) using phauxth?
3. I noticed there is a module called authorization, since this library handles just authentication and not authorization (please correct me if I'm wrong) wouldn't it be appropriate to rename it to `authentication.ex` instead?
Thank you.

**Comment by riverrun** [comment]
To answer 1 & 2 together, each function in Phauxth uses the `context` modules (new in Phoenix 1.3) that you specify -- it does not deal directly with the user models. It depends a lot on how you are setting up your app, but if you want to have a function that logs in just buyers, for example, you could use `Phauxth.Login.verify(params, MyApp.Buyer)` -- and for sellers it would be `Phauxth.Login.verify(params, MyApp.Seller)`.

As for the authorize module, that's just for the installer, and it's there to provide an example of how to use Phauxth. There's also an AuthorizeTest, and that's to check that my assumptions about the output of Phauxth are correct.

If you have any further questions, or if you have any difficulties setting up the multiple models, please let me know.

**Comment by dsignr** [comment]
Thanks a lot for the fast response and clarifications, @riverrun ! 
I should have clarified a bit more in detail; I am currently on an Umbrella setup, Phoenix 1.3 as well. So, I have a separate app dealing with authentication (let's call it `Gatekeeper`). 

`Gatekeeper` has a module defined as `People`. People has two models, a `buyer` and a `seller`.

The goal is to let each individual model login on its own. And each other should (and will have) separate routes, authorization rules (one shouldn't be able to access the other's dashboard and so on.

However, I also had confusion on how this would translate to storing values in a cookie. Would cookies of one model be picked up/confused for the other?

Also, a last request - do you have a sample application implementing this library

Thank you so much.

**Comment by riverrun** [comment]
First, the sample app -- at the moment there's just this simple [todo api](https://github.com/riverrun/phoenix-todoapp).

Now to the multiple user models. It depends a lot on your app, but here's an example scenario:

The login function uses the `get_by(attrs)` function in the context module. If you have this function decide which user model you are using, then you can have 'buyer' or 'seller' somewhere in the attrs, so the get_by function (in People) could be written like this:

    def get_by(%{"email" => email, "role" => "buyer"}) do
      let_the_buyer_in(email)
    end
    def get_by(%{"email" => email, "role" => "seller"}) do
      let_the_seller_in(email)
    end

If you want to use the Authenticate plug, then that uses the `get(id)` function in People. One idea might be to prefix the id when adding it to the session (instead of 1, you would use "buyer-1"), and then you can write a `get` function like this:

    def get("buyer" <> _ = id) do
      Repo.get(Buyer, id)
    end
    def get("seller" <> _ = id) do
      Repo.get(Seller, id)
    end

As for your question about cookies, as far as the Plug session is concerned, at any time there will only be one user in the session (for each device), and I think this is the kind of behavior that you would want, but I might have misunderstood your question.

Let me know how you get on. I would be interested in seeing how you set this app up.

**Comment by dsignr** [comment]
Thanks a lot for your detailed clarification and advice. I'm going to try the approach you've suggested tonight and share what worked for me soon. Thanks a lot! 👍

**Comment by dsignr** [comment]
An update on my progress:

I've managed to get the following working:
- Creation of users
- Login

However, here's where I've hit an odd roadblock - I have a protected resource cars at `/cars`.
This is my router:

```ruby
pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
  end

scope "/", Iam.Web do
    pipe_through :protected

    resources "/cars", CarController
end
```
Using the latest version of Phauxth:
```ruby
{:phauxth, "~> 0.12-rc"},
{:comeonin, "~> 4.0-rc"},
{:bcrypt_elixir, "~> 0.11"}
```
However, it seems that I'm able to access `/cars` resource without having to login. I even explicitly tried importing the authorize module in my controller as in the [sample app here](https://github.com/riverrun/phoenix-todoapp/blob/master/lib/todo_app/web/controllers/todo_controller.ex#L4). Inspecting the chrome panel shows no cookie either (and I deleted all of them). No luck. It seems none of the verification functions inside `authorize.ex` are being called, unless I'm missing something?

Will be happy to provide more information. Thanks :)

**Comment by riverrun** [comment]
Did you set up the app using the phauxth_new installer? That can give you a useful starting point.

I think the first problem is that the cookie is not being added to the session. After checking the password with Login.verify, you need to run the command `put_session(conn, :user_id, user.id)`, as in [this example](https://github.com/riverrun/phauxth/blob/master/installer/new/templates/session_controller.ex#L17).

The second problem is how to actually block users from accessing routes. I will add information about this to the wiki -- at [Authorization](https://github.com/riverrun/phauxth/wiki/Authorization).

Finally, you will need to update Phauxth to 0.13-rc -- there are a few changes that will make the advice I gave you yesterday work properly :)

**Comment by dsignr** [comment]
Hi David,
Thanks a lot :) Here's what I've done so far:
1. I setup the app using the new installer (replaced the old one).
2. I think the template already generated the `put_session` portion for me.
3. I tried this and have some updates:
    - When I added this line to my controller:
    - `def auth_action_id(conn, _), do: error(conn, :unauthorized, 401)`
    - I was hit with this error. `the :to option in redirect expects a path but was 401` I fixed it simply by passing a route instead of just 401 ([this line](https://github.com/riverrun/phauxth/blob/master/installer/new/templates/authorize.ex#L25)).
    - When I tried adding `def action(conn, _), do: auth_action(conn, __MODULE__)` in my controller, I am hit with `no function clause matching in Iam.Web.Authorize.auth_action/2`. Seems like a parameter mis-match.

Thanks a ton for your support so far! Really excited to work with this library!!

Cheers,
Neya

**Comment by riverrun** [comment]
Thanks for letting me know about the couple of errors in the Authorize module. I'll look into them as soon as possible.

**Comment by dsignr** [comment]
Hi @riverrun,
I managed to get the protected page working this weekend, by doing the following.

In my `cars` controller, I added the following:

```ruby
plug Phauxth.Authenticate
def action(conn, _), do: auth_action(conn, __MODULE__)
```

This eliminates the `no function clause matching in Iam.Web.Authorize.auth_action/2` error.

So, in essence, it seems like `plug Phauxth.Authenticate` I added in my routes isn't respected, therefore `current_user` wasn't being set (neither user nor nil), hence leading to that error.

Hope this helps.

**Comment by riverrun** [comment]
First of all, you can simplify the `pipeline` in web/router.ex file by writing something like this:

    pipeline :browser do
      plug :accepts, ["html"]
      plug :fetch_session
      plug :fetch_flash
      plug :protect_from_forgery
      plug :put_secure_browser_headers
    end

    pipeline :protected do
      plug Phauxth.Authenticate
    end

    scope "/", Iam.Web do
      pipe_through [:browser, :protected]
      resources "/cars", CarController
    end

About the Phauxth.Authenticate not being called, I'm not sure why that is. Is this in the dev or test environment?

**Comment by dsignr** [comment]
Hi @riverrun ,
Apologies for the delayed response. I had to re-work on my implementation. I am happy to report that everything is now resolved:

1) I was able to setup dual users (Buyers, Sellers) with ease - I just needed to clone the default scaffold and rename functions to make them specific for each user type. Eg. `get_buyer` instead of just `get`.

2) The router issue is resolved (it was in dev), I have no idea why it didn't work in the first place. I'm assuming it's because my setup is a little complex - I have a dedicated app in my umbrella setup that serves requests to the users, while rest of them are mostly domain specific. For example, there's a email module, posts module and finally IAM module which is where the library is installed.

3) I found working with your library such a breeze. A good example would be in the router, I was able to pass the `user_context` option like this: `plug Phauxth.Authenticate, user_context: Iam.Accounts`. That's so cool that I don't need to override anything to get this working.

4) I created a separate helper file where I override the default `verify` function:
```
  def verify_seller(%{"password" => password} = params) do
    Iam.Accounts.get_seller_by(params)
    |> check_pass(password, Comeonin.Bcrypt, [])
    |> log("successful login")
  end
```

And everything just works. I will keep this issue open till this weekend just to make sure everything is fixed and nothing is breaking. Once I finish my tests, I'll go ahead and close it. Once again, thanks so much for your assistance!

**Comment by riverrun** [comment]
Cool!

Just to let you know, there have been a few minor changes to Phauxth over the last couple of weeks, and I needed to change some names in the installer due to the changes in Phoenix 1.3-rc.3. Once Phoenix 1.3 is released, it should be fairly stable.

Also, there's a [gitter page](https://gitter.im/phauxth_elixir/Lobby) where we can discuss things.

**Comment by dsignr** [comment]
Hi @riverrun ,
I am still on the older RC's of the library and haven't tested the newer, updated versions yet. When I get a chance, I'll update the status here sometime this week. I'm also battling to keep up with the breaking changes in 1.3 (removal of `web` folder and introduction of `app_web` and corresponding nomenclature). Once I'm done, I'll update here.

Thank you :)

**Comment by dsignr** [comment]
Upgraded to 0.15 and was a breeze, no changes were needed. My only complain would be that currently if one needs to require login on specific controllers, then as per the docs, this is what I must do:
1. Add this to the controller
`def action(conn, _), do: auth_action(conn, __MODULE__)`

2. Add another parameter to the actions:
Previously:
```elixir
def index(conn, _params) do
...
end```

Now:
```elixir
def index(conn, _params, _) do
...
end```

The problem is that I have atleast 46 models and 70+ controllers (It's a massive app). And adding the third parameter is a huge pain. I tried something adding this to my controller:
`plug :auth_action`
But, it failed with parameters mis-match or something like that. 
It would be great to have a plug implementation rather than the above 2 steps (or please correct me if I'm wrong).

That's the only feedback as far as I got for now. Will keep you posted.

Cheers.

**Comment by riverrun** [comment]
You have a couple of options if you are not using the third argument in the controller functions:

1. You could rewrite `auth_action` so that it returns just the conn and params, so change
`apply(module, action_name(conn), [conn, params, current_user])` to
`apply(module, action_name(conn), [conn, params])`. You can still access the current_user information at `conn.assigns.current_user`.
2. You could use `plug :user_check` in the controller, after importing the Authorized module. There's an example of this [here](https://github.com/riverrun/phoenix-todoapp/blob/master/lib/todo_app_web/controllers/user_controller.ex).

**Comment by dsignr** [comment]
Thanks David for the fast response. So, in essence, my understanding is that`user_check` and `auth_action` are the same, but different only implementation-wise. Please correct me if I'm wrong.

Thank you.

**Comment by riverrun** [comment]
`user_check` and `auth_action` are used to achieve the same goal, but they do it in a different way.

user_check is a plug, so it takes the `conn` struct and options as input and returns the `conn` struct.

auth_action is a function that overrides the default action function. There's more information about this [here](https://hexdocs.pm/phoenix/Phoenix.Controller.html), especially in the 'Overriding action/2' section.

**Comment by dsignr** [comment]
That was very helpful. Thank you David :)

**Comment by dsignr** [comment]
Observation: For users who haven't confirmed their accounts and try to login, right now we say "Invalid credentials". Maybe we can display something along the lines of "You need to confirm your account first."?

**Comment by riverrun** [comment]
Closing this issue, but feel free to keep adding any comments you might have.

**Comment by dsignr** [comment]
Sure @riverrun , thanks for the splendid support so far! 👍

**Comment by WebDevFromScratch** [comment]
Hey @dsignr I now I'm (veeery) late to the party, but I'm doing something a bit similar and thought you might be able to maybe give me a hand.

The idea is: I'm implementing an app with a separate login for the admin panel, where only admins (users with a role of `admin`) should be able to access. I already read through this issue a few times and was able to implement separate logins but now I'm wondering about how to actually best go about authorization of the two separate parts of the app (I've kept my admin panel without any authorization for now).

I was thinking about storing something like `current_admin` instead of `current_user` in `conn` when I log my admin in and if I had that, everything else should probably be simple (in the admin authorization part, I would just check for the presence of `current_admin` and the user-facing side of things would remain as-is, looking at `current_user` for it's authorization rules). I'm wondering though, how to achieve such result? Would I need to implement yet another plug for it? How did you end up securing buyer/seller parts in the end (I didn't get that from the discussion above)? Maybe there is a better way than what I have in mind for this setup?

**Comment by dsignr** [comment]
There's a couple of ways to go about this depending on your setup.
Some quick questions:
1. Are you doing an umbrella?
2. Are you talking about regular authentication or token based authentication?

For regular authentication:
The current version of Phauxth makes it very easy to assign your own user model for authentication.
In fact, in my app, I don't use the default Phauxth user model any more.

The correct approach (and the one I used) is by having a role attribute on a single user model instead of maintaining multiple user models. Even for analytics purposes, the single user model works best. Multiple user models only make it unnecessarily complex for the same functionality, this was my conclusion.

Phauxth supports authorization out of the box. You just specify from within your controllers which roles should be accessible and which shouldn't and it takes care of the rest.

For token based authentication:
This is slightly complex in the sense that you need to code the parts for enabling access_token, refresh_token mechanisms, but once you've done it, the rest of it is similar to above. Unless you're using GraphQL, then it gets pretty complex, but still much easier than any other library out there.

**Comment by WebDevFromScratch** [comment]
Thanks for getting back to me (and how fast!) 🙇

I'm not doing an umbrella and am trying to set up a regular authentication. I've started with the single-model approach as well and this is how I have it set up right now, but I'm not yet sure how I want for the whole system to work.

My initial idea was, to have two separate logins (in an "admin" user case). Meaning that: when you log in to the "admin" segment of the app, this wouldn't actually influence the "client" segment, so I was thinking about keeping two separate session keys, one for each, or even expanding this idea, because my idea involves having to work with multiple client "organizations" that you should be required to log in separately, involving subdomains (e.g. `organization1.domain.com`, `organization2.domain.com` and an admin panel at `admin.domain.com` - I'm considering multi tenancy setup, but due to time constraints I didn't get into setting that yet). I suppose that maybe I'm trying to make this whole setup way too complicated and should think about something simpler for the MVP... Anyway, thanks for your answers so far, I might post more question in a couple of days when I try to move this forward again.

**Comment by dsignr** [comment]
Ok, no worries.

I recommend against two separate models for user, instead simply add another attribute 'role' as I mentioned before. Because, two different models mean you need to ensure the salts for generating session tokens need to be different, the maintenance for the two different models will also get you and you will find you will be writing duplicate code for both models which should be the same. Example, the code to get a admin and a regular user - essentially the same, the only difference being the model nomenclature. 

To understand the philosophy behind, all these complex nomenclature reasoning, I highly recommend you to read about DDD (Domain Driven Design) philosophy that talks a lot about this in depth. It may sound verbose at first, then after a while you can't imagine software design without it!
Here's a good book:
https://books.google.co.in/books/about/Domain_Driven_Design.html?id=hHBf4YxMnWMC&printsec=frontcover&source=kp_read_button&redir_esc=y#v=onepage&q&f=false

Multi-domain setup is unavoidable for certain apps, but you will have to ensure you don't allow users to create malicious subdomains, such as `support.domain.com` . I maintain a bare bones database for this purpose: https://github.com/dsignr/disallowed-usernames
Use it as a blacklist.

As for custom models, Phauxth allows for this by changing a line on your router file:
`plug MyAppWeb.Plugs.Phauxth, user_context: MyApp.IAM`
As you can see, I don't use the default `MyApp.Accounts` context that Phauxth generated for me.

Hope this helps :)

**Comment by WebDevFromScratch** [comment]
Yeah, I ended up with one `User` model, as well as one `Session` model in the end (at least for now) and simply re-thought authorization rules. Good tip about blacklisting usernames, I'll definitely use your list 👌Thanks again!
