### ISSUE TITLE
Error when submitting password forgotten without email

### ISSUE THREAD

**Issue by wernerlaude** [riverrun/phauxth#61]
Hi David.
I get a 500 when I submit the passwort_forgotten form without filling in an email..anything I can do?

**Comment by dikaio** [comment]
Hi @wernerlaude you could try a simple html validation so that it's checked before it's submitted `<input type="email" required>` and then in the password_reset_controller.ex add logic to check for an email and if no email supplied your provide an error message. [Here's an example of how that might look](http://nithinbekal.com/posts/phoenix-authentication/).

**Comment by riverrun** [comment]
@dikaio thanks for your help. @wernerlaude does that work?

**Comment by wernerlaude** [comment]
Thanks for support..I do that a little later.. some other prios..

**Comment by riverrun** [comment]
Did you get this to work?
